is_601_example_project/example_project/urls.py
from django.urls import path

from . import views

# urlpatterns = [
#     path('', views.index, name='index'),
#     path('/myGameLibrary', views.customPage, name='page'),
#     path('/bake',views.bake, name='bake'),
#     path('/display_image', views.display_image, name='image'),
#     path('/ajax', views.ajax, name="ajax"),
#     path('/ajax_demo', views.ajax_demo, name="ajax_demo"),
#     path('/my_ajax_view', views.my_ajax_view, name="my_ajax_view"),
# ]


router = routers.DefaultRouter()
router.register(r'ingredients', views.IngredientViewSet)
router.register(r'bakedGood', views.BakedGoodViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

is_601_example_project/is_601_example_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('example' , include('example_project.urls'))
]

is_601_example_project/example_project/models.py
from django.db import models
from django.forms import ModelForm

# Create your models here.

class Ingredients(models.Model):
    name=models.CharField(max_length=64)
    desc=models.CharField(max_length=256)

class BakedGood(models.Model):
    name = models.CharField(max_length=64)
    desc = models.CharField(max_length=256)
    good_type = models.CharField(
        max_length=2,
        choices=[
            ('BG',"Bagel"),
            ('BR',"Bread"),
            ('CO',"Cookie"),
            ('CA',"Cake"),
            ('PR',"Pretzel")
        ]
    )
    price = models.DecimalField(max_digits=6, decimal_places=2)
    recipe = models.TextField()
    ingredients = models.ManyToManyField(Ingredients)
    baked_on = models.DateTimeField()

    def _to_json(self):
        return {
            "name": self.name,
            "desc": self.desc,
            "good_type": self.good_type,
            "price": self.price,
            "recipe": self.recipe,
            # "ingredients": self.ingredients,
        }


class BakedGoodForm(ModelForm):
    class Meta:
        model = BakedGood
        fields = [
            'name',
            'desc',
            'good_type',
            'price',
            'recipe',
            'ingredients',
            'baked_on',
        ]

is_601_example_project/example_project/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .models import BakedGood, BakedGoodForm, Ingredients
from django.urls import reverse
from rest_framework import viewsets
from rest_framework import permissions
from . import serializers

# Create your views here.
def index(request):
    return HttpResponse("Hello, world.")

def customPage(request):
    context = {
        'title': 'My Game Library',
        'data': [
            {
                'name': 'Ghost of Tsushima',
                'rating': 'NA',
            },
            {
                'name': 'Spiderman 2',
                'rating': '5/5',
            },
            {
                'name': 'Last of Us',
                'rating': '4.5/5',
            },
            {
                'name': 'Horizon Zero Dawn',
                'rating': '4.5/5',
            }
        ]
    }
    return render(request, 'index.html', context)

def bakeryPage(request):
    baked_goods = BakedGood.objects.all()
    context = {
        'title': 'Bakery',
        'data': baked_goods
    }
    return render(request, 'example_app/', context)


def bake(request):
    if request.method == 'POST':
        form = BakedGoodForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('index'))
    else:
        form = BakedGoodForm()
    return render(request, 'bake.html', {'form': form})

def display_image(request):
    return render(request, 'display_image.html')

def ajax(request):
    return render(request, 'example_app/ajax.html')

def ajax_demo(request):
    data = {
        "this": 1,
        "is": 2,
        "JSON": 3,
    }

    return JsonResponse(data)

def my_ajax_view(request):
    data = []
    baked_goods = BakedGood.objects.all()
    for bg in baked_goods:
        data.append(bg._to_json())
    return JsonResponse({"bakedGood":data})


class IngredientViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Ingredients.objects.all()
    serializer_class = IngredientSerializer
    permission_classes = [permissions.IsAuthenticated]


class BakedGoodViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = BakedGood.objects.all()
    serializer_class = BakedGoodSerializer
    permission_classes = [permissions.IsAuthenticated]

is_601_example_project/example_project/templates/bake.html
{% extends 'base.html' %}

{% block title %}Bake Item{% endblock %}

{% block content %}
<p>Please use the following form to submit items that have been baked.</p>
<form action="{% url 'bake' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
<script>
    flatpickr("#id_baked_on", { enableTime: true, dateFormat: "Y-m-d H:i" }); 
</script>
{% endblock %}

is_601_example_project/example_project/templates/bakery.html
<!DOCTYPE html>

<html>

<head>

</head>

<body>
    <h1>Bakery</h1>
    <ul>
        {% for baked_good in baked_goods %}
        <li>{{ baked_good.name }} - {{baked_good.price}}</li>
        {% endfor %}
    </ul>
</body>

</html>

is_601_example_project/example_project/templates/base.html
<!DOCTYPE html>
<html>

{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <link rel="stylesheet" href="{% static 'app/style.css' %}">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>

<body>
    {% block content %}
    {% endblock %}
</body>

</html>

is_601_example_project/example_project/templates/display_image.html
{% extends 'base.html' %}

{% block title %}Display Image{% endblock %}

{% block content %}
{% load static %}
<img src="{% static 'pizza.jpg' %}" alt="pizza">
{% endblock %}

is_601_example_project/example_project/templates/index.html
<!DOCTYPE html>

<html>

<head>

</head>

<body>
    <h1>My Game Library</h1>
    <ul>
        {% for game in data %}
        <li>{{ game.name }} - {{game.rating}}</li>
        {% endfor %}
    </ul>
</body>

</html>